feat(dashboard): improve dashboard settings for user and tokens
hatchet-dev/hatchet pull request #275
Opened 2024-03-19 13:37 UTC by grutt

# Description

When using the password auth strategy there is no way for a user to update their password.

Fixes #274, #255 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## What's Changed

- [x] Render token list expiration as date
- [ ] Add update password mutation
- [ ] Add update password dialog and form

2024-03-19 22:50 UTC, abelanger5 requested changes

2024-03-19 22:50 UTC, abelanger5 commented on api-contracts/openapi/components/schemas/user.yaml
> +    - email
```suggestion
    - newPassword
```

2024-03-19 22:50 UTC, abelanger5 commented on api/v1/server/handlers/users/update_password.go
> +	ctx.Logger().Info("Body: ", request.Body)
Remove

2024-03-19 22:50 UTC, abelanger5 commented on api/v1/server/handlers/users/update_password.go
> +	existingUser := ctx.Get("user").(*db.UserModel)
It's better if this is at the top of the handler so we panic before starting any business logic

2024-03-19 22:50 UTC, abelanger5 commented on api/v1/server/handlers/users/update_password.go
> +	ctx.Logger().Info("existing user: ", existingUser)
Remove

2024-03-19 22:50 UTC, abelanger5 commented on api/v1/server/handlers/users/update_password.go
> +	err = authn.NewSessionHelpers(u.config).SaveAuthenticated(ctx, existingUser)
Shouldn't need this, this is just resaving the cookie

2024-03-19 22:50 UTC, abelanger5 commented on internal/repository/prisma/user.go
> +		txs = append(txs, r.client.UserPassword.UpsertOne(
Would be good to add an extra check that the user actually has a password set already. This could just be an `Update`. 

I don't think this is exploitable at the moment, but if things upstream change, there's potentially a way for a user to get a new password saved even with a different auth mechanism (like Google SSO) linked to their account. Perhaps by passing in an empty password and saving a new password. This would then allow someone to "reset" a password even if some other auth mechanism was linked.

2024-03-19 23:35 UTC, grutt commented on internal/repository/prisma/user.go
> +		txs = append(txs, r.client.UserPassword.UpsertOne(
good catch.

2024-03-19 23:36 UTC, grutt commented on frontend/app/src/pages/main/tenant-settings/components/members-columns.tsx
> +  if (user.metadata.id === row.original.metadata.id) {
@abelanger5 we should likely also guard here if its SSO, but currently this is not exposed on the user object. Any toughts?

2024-04-02 16:50 UTC, abelanger5 approved these changes

2024-04-02 16:50 UTC, merged