fix(python sdk): adds namespace config
hatchet-dev/hatchet pull request #288
Opened 2024-03-24 07:22 UTC by aeswibon

# Description

- Adds new namespace config to `python-sdk`  
- Fixes #279

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## What's Changed

- [ ] Add a list of tasks or features here...

2024-03-26 15:33 UTC, abelanger5 requested changes
Hey @aeswibon thanks for the PR! There are a few things which don't match up with the typescript SDK that I flagged. 

It might be easier if you make a separate PR for Python formatting and format all `.py` files via that PR. We can then merge that in ahead of this PR so it's easier to see what's changed.

2024-03-26 15:33 UTC, abelanger5 commented on python-sdk/hatchet_sdk/clients/events.py
> +        event_key = f"{self.namespace}:{event_key}"
This doesn't seem to match the implementation of the TS SDK: https://github.com/hatchet-dev/hatchet-typescript/blob/eaca1fcfd416665467a6fa8bcc0ac0989dd7512f/src/clients/event/event-client.ts#L33.

2024-03-26 15:33 UTC, abelanger5 commented on python-sdk/hatchet_sdk/worker.py
>          self.name = name
We should be modifying the `self.name` to be namespaced as well, to match the TS SDK: https://github.com/hatchet-dev/hatchet-typescript/pull/27/files#diff-2bba1bd36b8922955278a73eeaca7a34816e0ea0a63c498f0f6cfc028010f40d

2024-03-26 15:33 UTC, abelanger5 commented on python-sdk/hatchet_sdk/worker.py
>          self.name = name
Note that the `event_triggers` when creating the workflow should also be modified.

2024-03-26 17:20 UTC, aeswibon commented
Sure, I will open a PR to format all the `.py` files, then fixed all the changes suggested.

2024-04-11 14:38 UTC, grutt commented
tracking in #354

2024-04-11 14:38 UTC, closed without merging